language: c
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
arch:
 - amd64
 - ppc64le  
sudo: false
# Change this to your needs
script: aclocal && autoconf && automake --foreign --add-missing && ./configure && make all check
